Repository HSamiul/theologos, pull requests merged in 2023-04, with the labels that each got.

#53 Implemented Bible and Commentary split view, allowing users to view commentary and add commentary to bible verses
  accounts/views.py
  bible/templates/bible/index.html
  bible/urls.py
  bible/views.py
  commentary/forms.py
  commentary/migrations/0003_post_verse.py
  commentary/models.py
  theologos/settings.py
Labels: enhancement

#68 Implemented Post filtering by faith_tradition
  README.md
  bible/templates/bible/index.html
  bible/urls.py
  bible/views.py
  commentary/filters.py
  commentary/models.py
  commentary/test_models.py
  profiles/models.py
  theologos/settings.py
Labels: enhancement

#74 Updated README to be an exhaustive setup guide
  README.md
Labels: documentation

#84 Bible view
  commentary/templates/commentary/post_list.html
Labels: bug

#90 Implemented UX improvements across the app
  accounts/templates/accounts/register.html
  accounts/templates/accounts/user_update_form.html
  accounts/views.py
  bible/templates/bible/bible_list.html
  bible/templates/bible/bible_split_view.html
  bible/views.py
  profiles/validators.py
  static/base.css
  static/home.css
  static/nav_bar.css
  templates/base.html
  templates/home.html
  templates/partials/nav_bar.html
  templates/registration/login.html
  theologos/templates/messages.html
Labels: enhancement
